import type { RoutineTask } from "./schema";

export const FALLBACK_ROUTINE_TASKS: RoutineTask[] = [
  {
    step: 1,
    title_en: "Wash Hands",
    title_ja: "手洗い",
    description_en: "Wash your hands.",
    description_ja: "手を洗いましょう。",
    minutes: 5,
    youtubeUrl: "",
    emoji: "🧼",
  },
  {
    step: 2,
    title_en: "Eye Exercise",
    title_ja: "目の体操",
    description_en: "Do eye exercises.",
    description_ja: "目の体操をしましょう。",
    minutes: 10,
    youtubeUrl: "https://www.youtube.com/watch?v=dEsYUEG9yxA",
    emoji: "👀",
  },
  {
    step: 3,
    title_en: "Drink Water",
    title_ja: "水分補給",
    description_en: "Drink some water.",
    description_ja: "お水を飲みましょう。",
    minutes: 3,
    youtubeUrl: "",
    emoji: "💧",
  },
  {
    step: 4,
    title_en: "Stretch",
    title_ja: "ストレッチ",
    description_en: "Stretch your body.",
    description_ja: "ストレッチをしましょう。",
    minutes: 10,
    youtubeUrl: "https://www.youtube.com/watch?v=XgENmGTreU8",
    emoji: "🤸",
  },
  {
    step: 5,
    title_en: "Feeling Check",
    title_ja: "気分チェック",
    description_en: "How do you feel?",
    description_ja: "今の気分はどうですか？",
    minutes: 5,
    youtubeUrl: "",
    emoji: "😊",
  },
];
